spring:
  cloud:
    nacos:
      discovery:
        server-addr: 8.133.246.113:8848
        namespace: d750d92e-152f-4055-a641-3bc9dda85a29
        group: DEFAULT_GROUP
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
        file-extension: yaml
        refresh-enabled: true
# 日志文件配置
logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
